en:
  greeting_message: "Welcome to Gain, the world is a marketplace. To get started all we need is your location, please press the 'provide location' button below."
  farewell_message: "Bye! I'll miss you :("
